name: Variable
run-name: Variable
on: # Starting triggers
  workflow_dispatch: # Click from GitHub support
  pull_request: # After PR is created
  push: # After commit is pushed
env:
  MY_VARIABLE: jeejee
jobs:
  Example-Job: # Set of steps that are run on a VM
    runs-on: ubuntu-latest # type of vm
    steps:
      - name: Example # name of step
        run: echo "MY_VARIABLE $MY_VARIABLE and DEMO_SECRET ${{ secrets.SECRET_TOKEN }}"
